4 implement users contract
valuelogic/be-the-best-core pull request #10
Opened 2022-05-27 09:10 UTC by pobuchowskivl

2022-05-27 09:41 UTC, zblockowani commented on contracts/users/Users.sol
> +    event UpdatedUsersPoints(address walletAddress, int16 current_points);
W tych update'ach może zaznaczmy address walletu jako indexed, bo to coś w tym miejscu po czym może będziemy przeglądać jakaś historię w eventach

2022-05-27 09:41 UTC, zblockowani commented on contracts/model/Model.sol
> +        int16 points;
Tak teraz myślę, czy może na punkty jednak int32, wiem że 16 to całkiem sporo, ale w teorii jeśli apka ma działać długo to teoretycznie można to przekroczyć bo to jakieś 32tys?.
W sumie też zacząłem myśleć, czy chcemy mieć te minusowe punktu. Odejmować do 0 racja, ale zastanawiam się czy na - też, bo to może być bardzo demotywujące :D Ale to możemy jeszcze przegadać w sumie :)

2022-05-27 09:41 UTC, zblockowani commented on contracts/users/Users.sol
> +          SharedModel.User storage user = s_users[s_addresses[i]];
Tutaj memory nie storage. Storage to jakbyś chciał mieć bezpośrednio referencje, żeby np później zmienić wartość. Tak to tylko czytamy więc memory lepiej :)

Swoją drogą może od razu result[i] = s_users[s_addresses[i]]

2022-05-27 09:41 UTC, zblockowani commented on contracts/users/Users.sol
> +       require(s_users[msg.sender].isAdmin, "msg sender must be admin");
Może z tego require zrobić modifier, bo widzę, że przynajminej 3 razy jest użyty ten kod?

2022-05-27 09:41 UTC, zblockowani commented on contracts/users/Users.sol
> +       require(s_users[walletAddress].walletAddress == walletAddress, "User with passed wallet not exists");
Podobnie tutaj

2022-05-27 09:41 UTC, zblockowani commented on contracts/users/Users.sol
> +    address[] public s_addresses;
tutaj nie musi być public, bo getter chyba nie będzie wykorzystywany nigdzie do tej tablicy, poza tym kontraktem

2022-05-27 14:03 UTC, pobuchowskivl commented on contracts/users/Users.sol
> +    event UpdatedUsersPoints(address walletAddress, int16 current_points);
done

2022-05-27 14:05 UTC, pobuchowskivl commented on contracts/model/Model.sol
> +        int16 points;
zmienilem nawet do uint32 i dodalem dolna granice 0. Oczywiscie mozemy to potem jeszcze zmienic, ale tez wydaje mi sie, ze nie bedziemy nikogo karac punktami ujemnymi.

2022-05-27 14:05 UTC, pobuchowskivl commented on contracts/users/Users.sol
> +          SharedModel.User storage user = s_users[s_addresses[i]];
done

2022-05-27 14:05 UTC, pobuchowskivl commented on contracts/users/Users.sol
> +       require(s_users[msg.sender].isAdmin, "msg sender must be admin");
done

2022-05-27 14:05 UTC, pobuchowskivl commented on contracts/users/Users.sol
> +       require(s_users[walletAddress].walletAddress == walletAddress, "User with passed wallet not exists");
done

2022-05-27 14:05 UTC, pobuchowskivl commented on contracts/users/Users.sol
> +    address[] public s_addresses;
done

2022-05-30 07:04 UTC, maciejczekaj requested changes

2022-05-30 07:04 UTC, maciejczekaj commented on contracts/users/Users.sol
> +        require(bytes(nick).length < 21, "Nickname cannot have more than 20 bytes.");
skąd takie ograniczenie?

2022-05-30 07:04 UTC, maciejczekaj commented on contracts/model/Model.sol
> +        address walletAddress;
potrzebujemy tutaj adres skoro trzymamy go w mappingu?

2022-05-30 07:04 UTC, maciejczekaj commented on contracts/users/Users.sol
> +            s_users[walletAddress].walletAddress,
pobrałbym te dane z parametrów wejściowych, żeby nie płacić za odczyt ze storage

2022-05-30 07:08 UTC, pobuchowskivl commented on contracts/model/Model.sol
> +        uint32 points;
przy dodawaniu punktow mamy ograniczenie, ze jesli wynik wychodzi mniej niz 0 to zapisujemy 0, zobacz https://github.com/valuelogic/be-the-best-core/pull/10#discussion_r883445076

2022-05-30 07:08 UTC, pobuchowskivl commented on contracts/users/Users.sol
> +        require(bytes(nick).length < 21, "Nickname cannot have more than 20 bytes.");
po prostu dodalem jakiekolwiek ograniczenie, zeby ktos nam tutaj Pana Tadeusza nie wkleil :)

2022-05-30 07:10 UTC, pobuchowskivl commented on contracts/users/Users.sol
> +            s_users[walletAddress].walletAddress,
Chcialem wlasnie pobrac ze storage, zeby byc pewien, ze dokladnie z tymi parametrami zostal zalozony user -> dowod, ze dostalismy to czego zadalismy, bez magicznej logiki pomiedzy

2022-05-30 07:11 UTC, pobuchowskivl commented on contracts/model/Model.sol
> +        address walletAddress;
tak, bedziemy wysylac calego Usera z addressem do frontow

2022-05-30 15:49 UTC, maciejczekaj commented on contracts/users/Users.sol
> +        emit UpdatedUsersPoints(walletAddress, s_users[walletAddress].points);
w tej funkcji i funkcji wyżej emitujemy dwie różne wartości w evencie (points jako zmianę, a tutaj całkowitą liczbę punktów usera). Raczej chcemy, zeby działało tak jak tutaj.

2022-05-31 07:28 UTC, zblockowani approved these changes

2022-06-02 05:30 UTC, maciejczekaj approved these changes

2022-06-02 07:41 UTC, ptrepkaVL approved these changes

2022-06-02 11:44 UTC, merged